//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Application.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Application.Utilities.Resource_Message", typeof(Resource_Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanNotInsertAlreadyExist_{0}.
        /// </summary>
        public static string CanNotInsertAlreadyExist {
            get {
                return ResourceManager.GetString("CanNotInsertAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanNot_Insert_Character_Less_{0}.
        /// </summary>
        public static string CanNotInsertCharacterLess {
            get {
                return ResourceManager.GetString("CanNotInsertCharacterLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoNotAccess_{0}.
        /// </summary>
        public static string DoNotAccess {
            get {
                return ResourceManager.GetString("DoNotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit_Info_Success_IsDone.
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_{0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه {0} را وارد نمایید.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_Incorrect.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This_Action_NotAllow_{0}.
        /// </summary>
        public static string IncorrectAction {
            get {
                return ResourceManager.GetString("IncorrectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert_Info_Success_IsDone.
        /// </summary>
        public static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model_IsEmpty.
        /// </summary>
        public static string ModelIsEmpty {
            get {
                return ResourceManager.GetString("ModelIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info_NotFound_{0}.
        /// </summary>
        public static string NotFoundInfo {
            get {
                return ResourceManager.GetString("NotFoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound_Method_{0}.
        /// </summary>
        public static string NotFoundMethod {
            get {
                return ResourceManager.GetString("NotFoundMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound_Service_{0}.
        /// </summary>
        public static string NotFoundService {
            get {
                return ResourceManager.GetString("NotFoundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_NotFound_{0}.
        /// </summary>
        public static string NotFoundUser {
            get {
                return ResourceManager.GetString("NotFoundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter_IsEmputy_{0}.
        /// </summary>
        public static string ParameterIsEmputy {
            get {
                return ResourceManager.GetString("ParameterIsEmputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did_From_{0}_Sure.
        /// </summary>
        public static string QuestionAreSure {
            get {
                return ResourceManager.GetString("QuestionAreSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback_{0}.
        /// </summary>
        public static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback_DataLog.
        /// </summary>
        public static string RollbackDataLog {
            get {
                return ResourceManager.GetString("RollbackDataLog", resourceCulture);
            }
        }
    }
}
